/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://r5nnwgn3trcvjn7qvsy3jli774.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-oqo6xpwqjjfchmx3qzphxbzlra",
    "aws_cognito_identity_pool_id": "us-west-2:4a3cbef3-c82f-4ae3-a12e-6d8b21e73c92",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_Jz9d3n1Pl",
    "aws_user_pools_web_client_id": "1uohhfuu0ts6lbf4edjtbevjrc",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
